"""Pydantic models for validating optimizer docstrings.

This module contains Pydantic models generated from the JSON schema
defined in docs/schemas/docstring-schema.json. These models provide
type-safe validation for optimizer docstrings following the COCO/BBOB
template.

Generated by datamodel-codegen:
  filename:  docstring-schema.json
  timestamp: 2025-12-24T14:03:22+00:00
"""

from __future__ import annotations

from enum import Enum
from enum import IntEnum

from pydantic import AnyUrl
from pydantic import BaseModel
from pydantic import Field


class AlgorithmClass(Enum):
    """Category of algorithm"""

    swarm_intelligence = "Swarm Intelligence"
    evolutionary = "Evolutionary"
    gradient_based = "Gradient-Based"
    classical = "Classical"
    metaheuristic = "Metaheuristic"
    physics_inspired = "Physics-Inspired"
    probabilistic = "Probabilistic"
    social_inspired = "Social-Inspired"
    constrained = "Constrained"
    multi_objective = "Multi-Objective"
    multi_objective_decomposition = "Multi-Objective Decomposition"


class Property(Enum):
    population_based = "Population-based"
    single_solution = "Single-solution"
    derivative_free = "Derivative-free"
    gradient_based = "Gradient-based"
    stochastic = "Stochastic"
    deterministic = "Deterministic"
    adaptive = "Adaptive"
    parallel_capable = "Parallel-capable"
    decomposition_based = "Decomposition-based"
    neighborhood_search = "Neighborhood search"
    archive_based = "Archive-based"


class AlgorithmMetadata(BaseModel):
    """Algorithm Metadata block (table format in docstring)"""

    algorithm_name: str = Field(..., description="Full algorithm name")
    acronym: str = Field(
        ...,
        description="Short acronym (e.g., PSO, GA, CMA-ES)",
        pattern="^[A-Z][A-Z0-9-]*$",
    )
    year_introduced: int = Field(
        ..., description="Year the algorithm was first published", ge=1900, le=2100
    )
    authors: str = Field(
        ..., description="Authors in format: Last, First; Last2, First2"
    )
    algorithm_class: AlgorithmClass = Field(..., description="Category of algorithm")
    complexity: str = Field(
        ...,
        description="Time complexity using LaTeX notation (e.g., 'O(n $\\times$ m)')",
    )
    properties: list[Property] = Field(..., description="Algorithm properties")
    implementation: str | None = Field(
        "Python 3.10+", description="Implementation language and version"
    )
    coco_compatible: bool | None = Field(
        True, description="Whether algorithm is COCO/BBOB compatible"
    )


class Variable(BaseModel):
    symbol: str = Field(..., description="LaTeX symbol (e.g., '$x_t$')")
    description: str


class BoundaryConditions(Enum):
    clamping = "clamping"
    reflection = "reflection"
    periodic = "periodic"
    penalty = "penalty"


class ConstraintHandling(BaseModel):
    boundary_conditions: BoundaryConditions | None = None
    feasibility_enforcement: str | None = None


class MathematicalFormulation(BaseModel):
    """Mathematical formulation section with LaTeX equations"""

    core_equation: str | None = Field(
        None, description="Main update equation in LaTeX (display math $$ ... $$)"
    )
    variables: list[Variable] | None = Field(None, description="Variable definitions")
    constraint_handling: ConstraintHandling | None = None


class TableItem(BaseModel):
    parameter: str
    default: str | float | bool | None
    bbob_recommended: str | None = None
    description: str


class Impact(Enum):
    high = "High"
    medium = "Medium"
    low = "Low"


class SensitivityAnalysis(BaseModel):
    parameter: str | None = None
    impact: Impact | None = None
    notes: str | None = None


class Hyperparameters(BaseModel):
    """Hyperparameters table and sensitivity analysis"""

    table: list[TableItem] | None = None
    sensitivity_analysis: list[SensitivityAnalysis] | None = Field(
        None, description="Sensitivity notes for each parameter"
    )


class DimensionsTestedEnum(IntEnum):
    integer_2 = 2
    integer_3 = 3
    integer_5 = 5
    integer_10 = 10
    integer_20 = 20
    integer_40 = 40


class SearchSpace(BaseModel):
    dimensions_tested: list[DimensionsTestedEnum] | None = [2, 3, 5, 10, 20, 40]
    bounds: str | None = Field(None, description="Typical bounds description")
    instances: int | None = Field(15, description="Number of instances per function")


class EvaluationBudget(BaseModel):
    budget_formula: str | None = Field(
        None, description="Budget formula (e.g., 'dim * 10000')"
    )
    independent_runs: int | None = 15
    seeds: str | None = Field("0-14", description="Seed range description")


class PerformanceMetric(Enum):
    target_precision = "target_precision"
    success_rate = "success_rate"
    expected_running_time = "expected_running_time"
    hypervolume = "hypervolume"
    inverted_generational_distance = "inverted_generational_distance"
    spread = "spread"
    epsilon_indicator = "epsilon_indicator"


class COCOBBOBSettings(BaseModel):
    """COCO/BBOB Benchmark Settings section"""

    search_space: SearchSpace | None = None
    evaluation_budget: EvaluationBudget | None = None
    performance_metrics: list[PerformanceMetric] | None = None


class Example(BaseModel):
    """Example section with doctest code"""

    description: str | None = Field(None, description="Introductory text before code")
    code: str | None = Field(
        None, description="Doctest code block (>>> prefixed lines)"
    )
    requires_seed: bool | None = Field(
        True, description="Whether example must include seed=42"
    )


class Parameter(BaseModel):
    """Single parameter definition - description MUST start on same line as name"""

    name: str = Field(..., description="Parameter name")
    type: str = Field(
        ...,
        description="Type annotation (e.g., 'int', 'float', 'Callable[[ndarray], float]')",
    )
    optional: bool | None = False
    default: str | float | bool | None = Field(
        None, description="Default value if optional"
    )
    description: str = Field(
        ..., description="Description - MUST be on same line as 'name (type):'"
    )
    bbob_guidance: str | None = Field(None, description="BBOB-specific recommendations")


class Attributes(BaseModel):
    """Instance attributes section"""

    attributes: list[Parameter]


class Component(BaseModel):
    """Return value component for tuple returns."""

    name: str | None = None
    type: str | None = None
    description: str | None = None


class Returns(BaseModel):
    """Returns section - type description MUST have inline summary"""

    type: str | None = Field(None, description="Return type annotation")
    description: str | None = Field(
        None, description="Description - MUST be on same line as type"
    )
    components: list[Component] | None = Field(
        None, description="Sub-components for tuple returns (indented list)"
    )


class ExceptionInfo(BaseModel):
    """Exception information for Raises section."""

    type: str = Field(..., description="Exception type name")
    description: str = Field(..., description="When this exception is raised")


class Raises(BaseModel):
    """Raises section."""

    exceptions: list[ExceptionInfo] | None = None


class Citation(BaseModel):
    """Citation information for References section."""

    number: int = Field(..., description="Citation number [1], [2], etc.")
    authors: str
    year: int
    title: str
    journal: str | None = Field(None, description="Journal name (italic in docstring)")
    volume: str | None = None
    pages: str | None = None
    doi: str | None = Field(None, pattern="^https?://doi\\.org/")


class CocoDataArchive(BaseModel):
    """COCO data archive links."""

    benchmark_results_url: AnyUrl | None = None
    algorithm_data_url: AnyUrl | None = None
    code_repository_url: AnyUrl | None = None


class Implementation(BaseModel):
    """Implementation reference information."""

    original_paper_code_url: AnyUrl | None = None
    notes: str | None = None


class References(BaseModel):
    """References section with academic citations and links"""

    citations: list[Citation] | None = None
    coco_data_archive: CocoDataArchive | None = None
    implementation: Implementation | None = None


class RelatedAlgorithm(BaseModel):
    """Related algorithm information for See Also section."""

    name: str
    description: str
    bbob_comparison: str | None = None


class SeeAlso(BaseModel):
    """See Also section linking related algorithms"""

    related_algorithms: list[RelatedAlgorithm] | None = None
    base_classes: list[str] | None = None
    related_modules: list[str] | None = None


class Format(Enum):
    """Simple = bullet list, Structured = bold headers with sublists"""

    simple = "simple"
    structured = "structured"


class Item(BaseModel):
    """Notes item with optional label and value."""

    label: str | None = Field(
        None, description="Item label (rendered as **bold** if present)"
    )
    value: str | None = Field(None, description="Item value/description")


class NotesSubsection(BaseModel):
    """A subsection within Notes (rendered with **bold header**)"""

    header: str | None = Field(None, description="Header text (without ** markers)")
    items: list[Item] | None = None


class Args(BaseModel):
    """Arguments section - parameters must have inline descriptions"""

    parameters: list[Parameter]


class Method(BaseModel):
    """Method documentation."""

    name: str
    signature: str = Field(
        ..., description="Method signature (e.g., 'search() -> tuple[ndarray, float]')"
    )
    description: str = Field(
        ..., description="Description - MUST be on same line after signature"
    )
    returns: Returns | None = None
    raises: Raises | None = None
    notes: list[str] | None = None


class Methods(BaseModel):
    """Methods section documenting class methods"""

    methods: list[Method] | None = None


class StructuredNotes(BaseModel):
    """Structured notes with subsections (bold headers)"""

    computational_complexity: NotesSubsection | None = None
    bbob_performance_characteristics: NotesSubsection | None = None
    convergence_properties: NotesSubsection | None = None
    reproducibility: NotesSubsection | None = None
    pareto_front_characteristics: NotesSubsection | None = None
    implementation_details: NotesSubsection | None = None
    known_limitations: NotesSubsection | None = None
    version_history: NotesSubsection | None = None


class Notes(BaseModel):
    """Notes section - supports two formats: simple list or structured subsections"""

    format: Format | None = Field(
        None,
        description="Simple = bullet list, Structured = bold headers with sublists",
    )
    simple_notes: list[str] | None = Field(
        None, description="Simple bullet point notes"
    )
    structured_notes: StructuredNotes | None = Field(
        None, description="Structured notes with subsections (bold headers)"
    )


class CocoBbobOptimizerDocstringSchema(BaseModel):
    """JSON Schema for validating and structuring optimizer docstrings in Google style for the useful-optimizer library"""

    field_schema: str | None = Field(
        None, alias="$schema", description="JSON Schema reference"
    )
    summary: str | None = Field(
        None,
        description="One-line summary of the algorithm (first line of docstring)",
        max_length=80,
    )
    extended_description: str | None = Field(
        None, description="Extended description after blank line following summary"
    )
    algorithm_metadata: AlgorithmMetadata
    mathematical_formulation: MathematicalFormulation | None = None
    hyperparameters: Hyperparameters | None = None
    coco_bbob_benchmark_settings: COCOBBOBSettings
    example: Example
    args: Args
    attributes: Attributes
    methods: Methods | None = None
    returns: Returns | None = None
    raises: Raises | None = None
    references: References
    see_also: SeeAlso | None = None
    notes: Notes
